### PR TITLE
Update and rename focusserver.py to SPIRO_live_view.py

### PR DESCRIPTION
**Pull request by AlyonaMinina**
Further changes:

1. Links-> buttons
2. Place buttons according to the direction they indicate
3. Sync initial position with spiro.py
4. Sync focusing values with spiro.py. Please, make sure focusing values are taken into account for EVERY shot (implemented after exposure assessment?)
5. Check box for the reference grid
6. Add stop button to live view to stop recording + 6 sec power nap for the camera before user presses Ctrl+C

**Suggestion for an automated alignment script, since you like OpenCV so much**

- find the tiny dick (it is bolted to the cube now, so we can estimate approx. how many steps it is away from the initial position)
- make estimated number of steps
- Match reference points or text on the cube (scale bar should be always in the pic?) to the existing reference grid
- If doesn't match make more steps or step back (is it possible to estimate what direction and is preferential?)
- Re-match, if ok-> write the total n of steps made from tiny dick to the initial position into spiro.py

### CODE REVIEW

**Comment by jonasoh** [comment]
I don't see the point of this pull request. Please submit feature requests as issues!

**Comment by AlyonaMinina** [comment]
jonas, please read the changes in the script/file name before closing a pull request. you still have Petripi all over it

**Comment by jonasoh** [comment]
The pull request contains numerous problems and I didn't like the thought of importing code in this state. I will look into this myself but please create an issue for the proposed web UI fixes at least.

**Comment by AlyonaMinina** [comment]
do you want me to make another pull request with the patch only? )

**Comment by jonasoh** [comment]
No, don't bother. Most parts of the patch shouldn't be included in the code (first comment is wrong so should anyway be changed, no need to import "time", specific message for quitting with keyboard interrupt should not need changing, no need for changing cam to camera on the last line (the block is within the scope of focusserver.focusServer() (though it may look cleaner).…)

Appreciate the web UI comments though but please put them in an Issue instead.

**Pull request closed without merging**
